version: '3.8'
services:
  frontend:
    build:
      context: ./src
      dockerfile: frontend/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - './src/shared:/app/shared'
      - './src/frontend/src:/app/frontend/src'
      - './src/frontend/public:/app/frontend/public'
  gameserver:
    build:
      context: ./src
      dockerfile: backend/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - './src/backend:/app/backend'
      - './src/shared:/app/shared'
  fish-processor:
    build:
      context: ./src
      dockerfile: backend/src/fish-processor/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - './src/backend:/app/backend'
      - './src/shared:/app/shared'
  boat-processor:
    build:
      context: ./src
      dockerfile: backend/src/boat-processor/Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - './src/backend:/app/backend'
      - './src/shared:/app/shared'
