version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15675:15675" # Web MQTT
            - "15672:15672" # Management plugin
            - "1883:1883" # MQTT
        volumes:
            - "./src/middlelayer/etc/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    frontend:
        build:
            context: ./src
            dockerfile: frontend/Dockerfile.dev
        ports:
            - "5173:5173"
        volumes:
            - "./src/frontend/src:/app/frontend/src"
            - "./src/shared:/app/shared"
        depends_on:
            - rabbitmq
    gameserver:
        build:
            context: ./src
            dockerfile: backend/Dockerfile.dev
        stdin_open: true
        tty: true
        volumes:
            - "./src/backend:/app/backend"
            - "./src/shared:/app/shared"
        depends_on:
            - rabbitmq
