FROM node:lts

WORKDIR /app

COPY ./shared/package.json ./shared/
RUN cd shared && npm install

COPY ./frontend/package.json ./frontend/
RUN cd frontend && npm install

COPY ./shared ./shared

COPY ./frontend ./frontend

EXPOSE 5173

VOLUME [ "/app/shared/node_modules" ]
VOLUME [ "/app/frontend/node_modules" ]

WORKDIR /app/frontend

CMD [ "npm", "run", "dev" , "--", "--host"]